### ISSUE TITLE
嵌入式版怎么指定交叉编译器

### ISSUE THREAD

**Issue by zgq91** [jinfagang/simpleocv#3]

**Comment by lucasjinreal** [comment]
cmake 里面指定aarch64，可以百度一下怎么交叉编译

**Comment by zgq91** [comment]
用交叉编译后报错
opt/linux/x86-arm/aarch64-mix210-linux/host_bin/../lib/gcc/aarch64-linux-gnu/7.3.0/../../../../aarch64-linux-gnu/bin/ld: CMakeFiles/demo_color.dir/demo_color.cc.o: in function `cv::Mat::release()':
demo_color.cc:(.text._ZN2cv3Mat7releaseEv[_ZN2cv3Mat7releaseEv]+0x4c): undefined reference to `sim::fastFree(void*)'
/opt/linux/x86-arm/aarch64-mix210-linux/host_bin/../lib/gcc/aarch64-linux-gnu/7.3.0/../../../../aarch64-linux-gnu/bin/ld: ../libsimpleocv.so: undefined reference to `pthread_key_create'
/opt/linux/x86-arm/aarch64-mix210-linux/host_bin/../lib/gcc/aarch64-linux-gnu/7.3.0/../../../../aarch64-linux-gnu/bin/ld: ../libsimpleocv.so: undefined reference to `pthread_key_delete'
collect2: error: ld returned 1 exit status
examples/CMakeFiles/demo_color.dir/build.make:95: recipe for target 'examples/demo_color' failed
